### ISSUE TITLE
1.19.2 Update URL is no longer valid 

### ISSUE THREAD

**Issue by CKY-** [dragon-forge/SolarFluxReborn#12]
https://github.com/dragon-forge/SolarFluxReborn/blob/5bfd9e11f16af0e64e8c0eed46c8c979f9ce7eb9/src/main/resources/META-INF/mods.toml#L10
seems that the URL for the update JSON is not valid anymore? can you please fix this?

**Comment by Zeitheron** [comment]
Heroku took down my mod update checking service, so it no longer works. has to be replaced with something more robust.
I'll think of something.
