### ISSUE TITLE
Game crashes when trying to upgrade a solar panel with the twi-light upgrade

### ISSUE THREAD

**Issue by xPotato4u** [dragon-forge/SolarFluxReborn#13]
As the title says, the game crashes when you try to twi-light upgrade them

**Comment by Zeitheron** [comment]
Need more info. This is just useless without a crash report.

**Comment by xPotato4u** [comment]
[debug.log](https://github.com/dragon-forge/SolarFluxReborn/files/12296319/debug.log)
[latest.log](https://github.com/dragon-forge/SolarFluxReborn/files/12296320/latest.log)
[crash-2023-08-08_23.44.48-server.txt](https://github.com/dragon-forge/SolarFluxReborn/files/12296322/crash-2023-08-08_23.44.48-server.txt)

I hope this is fine like that.
