### ISSUE TITLE
[1.18.2] Mod compatibility not working

### ISSUE THREAD

**Issue by gregoryeple** [dragon-forge/SolarFluxReborn#14]
**Version**
`SolarFluxReborn-1.18.2-18.2.4`
`HammerLib-1.18.2-18.2.16`

**No new solar panels or upgrades are added when other compatible mods are present.**
For example, neither the **Wyvern Solar Panel** nor the **Twi-Light Upgrade** are present in-game despite having **Draconic Evolution** and **The Twilight Forest** installed.

The compatibility was tested with the following mods:
- `appliedenergistics2-forge-11.7.4`
- `Avaritia-1.18.2-4.0.1.6-universal`
- `Draconic-Evolution-1.18.2-3.0.29.524-universal`
- `twilightforest-1.18.2-4.1.1494-universal`

This was also tested in 1.16.5 and in 1.19.2 and the compatibilities worked perfectly for those versions.

**Comment by Zeitheron** [comment]
1.18 os no longer supported, sorry.
