### ISSUE TITLE
Curios Support

### ISSUE THREAD

**Issue by uhloin** [dragon-forge/SolarFluxReborn#15]
It would be good, if SFR support charge items in curios slots, not only in inventory.
How to reproduce:
MC version 1.20.1
Forge version 41.1.76 (NeoForge)
SolarFluxReborn 20.1.2
curios-forge 5.3.1
Use Solar Panel V with Dispersive Upgrade
Use Wireless Universal Grid (see https://www.curseforge.com/minecraft/mc-mods/universal-grid)
If Grid is in inventory, it recharges; if grid is in the Back curios slot, then not.

**Comment by Zeitheron** [comment]
This is a good idea, will implement it with next build of HammerLib.

**Comment by uhloin** [comment]
thank you :)

**Comment by Zeitheron** [comment]
![image](https://github.com/dragon-forge/SolarFluxReborn/assets/38943617/e1c7d93d-9cb6-4ba2-9c77-858afb87792f)

Done.

**Comment by Zeitheron** [comment]
The 1.20.1 binary can be obtained from Modrinth https://modrinth.com/mod/hammer-lib/version/20.1.14

**Comment by uhloin** [comment]
yes, it works, thank you
