### ISSUE TITLE
Furnace Upgrade is non functional?

### ISSUE THREAD

**Issue by korAPUcard** [dragon-forge/SolarFluxReborn#16]
MC: 1.20.1
Forge: Latest version

I have crafted Furnace Upgrade but and I tried to use it, but nothing happened.
Is this a work in progress or something I missed?
I can't figure out how to use it.

**Comment by Zeitheron** [comment]
How did you use it? Please provide a screenshot.

**Comment by korAPUcard** [comment]
> How did you use it? Please provide a screenshot.

I said "Nothing happened". Which mean, No any "use action" animation. I'm just right clicked this item to furnace, but it didn't installed. No use action and nothing happened, just happened 'open the vanilla furnace GUI'. Tried to combine in crafting table, but you know, there is no recipe. So I can't combine it. Then I tried to Shift + Right click items to furnace. Vanilla GUI not opened but still same, no use action and nothing happened.

Then I thought "maybe I missed something" and tried putting the item in the furnace, but still nothing happened and it never went in in the first place.

Literally “nothing happened”. The phenomenon literally looked like a dummy data item with no function, with only a recipe for combination.

**Comment by korAPUcard** [comment]
Oh, I just closed the issue by mistake. The problem hasn't been resolved yet.

Anyway, there is no reason to add items that don't currently work to your current build. If the item was still under development, there would have been a way to add the phrase WIP or hide the item altogether.

**Comment by Zeitheron** [comment]
The item clearly works, you don't know how and assume it's broken already, or WIP.

It is a panel upgrade, not a furnace upgrade.
Put it into a solar panel above a furnace.
