### ISSUE TITLE
textures wont load

### ISSUE THREAD

**Issue by evilcarrotoverlord** [dragon-forge/SolarFluxReborn#17]
i tried pretty much everything but the custom panels wont load the textures
the log says 
[22:24:23] [Worker-ResourceReload-8/WARN]: Missing textures in model solarflux:sp_custom_9#:
    minecraft:textures/atlas/blocks.png:solarflux:block/sp_custom_9_base
    minecraft:textures/atlas/blocks.png:solarflux:block/sp_custom_9_top
[22:24:23] [Worker-ResourceReload-8/WARN]: Missing textures in model solarflux:sp_custom_X#:
    minecraft:textures/atlas/blocks.png:solarflux:block/sp_custom_X_base
    minecraft:textures/atlas/blocks.png:solarflux:block/sp_custom_X_top

![image_2023-11-04_222617166](https://github.com/dragon-forge/SolarFluxReborn/assets/40693719/37fd9e68-7beb-43a1-a408-ccd5674ae5c7)
i have these files in every folder i in the solarfux config section not sure what else to name them
[
![image](https://github.com/dragon-forge/SolarFluxReborn/assets/40693719/76977953-fc70-47e9-b4e1-2f517b8743a0)
](url)

current config folder
[https://pixeldrain.com/u/9M5uNNjw](url)

**Comment by Zeitheron** [comment]
[this guide is still relevant.](https://youtu.be/WVr6-3E7lA8)

**Comment by evilcarrotoverlord** [comment]
then what did i do wrong?
the guide shows it should be 9_top.png in the textures folder
but the mod comes with example textures in the blocks folder 
i have the textures in both folders
btw the example also didnt load its textures when i uncomment it thats why i assumed the naming changed
[
![image](https://github.com/dragon-forge/SolarFluxReborn/assets/40693719/a6ded449-b810-4b23-b809-d6101af8df43)
](url)

**Comment by Zeitheron** [comment]
This was a bug in 1.20.1, it was since fixed. Sorry for misunderstanding.
