### ISSUE TITLE
Changes made in config don't seem to take effect

### ISSUE THREAD

**Issue by MrRedstoneA1** [dragon-forge/SolarFluxReborn#2]
Specifically, trying to change how much energy each panel can produce and store doesn't seem to actually affect the panels. They still report default values.

Mod version is 12.4.11 for Minecraft 1.12.2

**Comment by Zeitheron** [comment]
1.12.2 is out of active development.

**Comment by MrRedstoneA1** [comment]
Well, I guess it's just gonna remain like that then.
