### ISSUE TITLE
Kubejs and Solar Flux compat

### ISSUE THREAD

**Issue by DrollestDuck88** [dragon-forge/SolarFluxReborn#21]
Hi, 

I would like to know if there is any kubejs support with this mod(Solar Flux Reborn)… (i play in 1.18.2 (that was me for the solar panels draconic and avaritia) im still trying (I was not thinking about it until a mod pack was released and I played it and it had the panels added to it) and Im using kubejs to add the panels recipes to the game and it doesn’t seem to work (or something else isn’t working right…(I just need help with that)) 

Note that i will ask kubejs’s devs for that too…

Thanks in advance… 
DrollestDuck88

**Comment by Zeitheron** [comment]
1.18.2 is not supported, sorry.
In later versions HammerLib offers a way to disable any recipe added by my mods without kjs.

**Comment by DrollestDuck88** [comment]
But would I here be a way to do it with Kubejs?? Or something else?

**Comment by Zeitheron** [comment]
If you're seeking for adding recipes, the builtin js file allows adding custom recipes right there within the mod itself, if that would help.

**Comment by DrollestDuck88** [comment]
I need to test that out but idk if it detects the other mods already…

**Comment by DrollestDuck88** [comment]
Does it detects draconic and avaritia?

**Comment by Zeitheron** [comment]
there is an example commented out, it's quite easy to do there.

**Comment by DrollestDuck88** [comment]
> there is an example commented out, it's quite easy to do there.

If you understand… I understand but not all… and the video doesn’t show every possibilities…

**Comment by DrollestDuck88** [comment]
Or just how to do them…

**Comment by Zeitheron** [comment]
You can ask on our discord support server for help if you need any.
