### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by ghost** [dragon-forge/SolarFluxReborn#29]
it crashes on launch, my friend has the exact same mods but it works for him

im using version 1.16.5 and version 16.5.11 of the mod
crash log: [crash-2024-06-06_18.15.36-fml.txt](https://github.com/user-attachments/files/15653396/crash-2024-06-06_18.15.36-fml.txt)
crash: ![image](https://github.com/dragon-forge/SolarFluxReborn/assets/163568638/cf4c13da-0001-4b2d-9b37-7a5bf101e9a2)

**Comment by Zeitheron** [comment]
Java 22 is not supported with 1.16.5. Use Java 8.
