### ISSUE TITLE
[1.12.2] SolarFluxAPI.SOLAR_PANELS" is null

### ISSUE THREAD

**Issue by Igor5877** [dragon-forge/SolarFluxReborn#35]
I have installed Cleanroom forge and that's why I'm working with 21 java and this error
[crash-2024-08-17_21.29.38-client.txt](https://github.com/user-attachments/files/16646207/crash-2024-08-17_21.29.38-client.txt)

**Comment by Zeitheron** [comment]
1.12.2 does not work with Java 21. Use Java8

**Comment by Igor5877** [comment]
I installed with the help of https://github.com/CleanroomMC/Cleanroom

**Comment by Zeitheron** [comment]
This does not promise compatibility with other mods.

**Comment by Zeitheron** [comment]
Try using [Fugue](https://github.com/CleanroomMC/Fugue)

**Comment by Igor5877** [comment]
I have it
