### ISSUE TITLE
MC 1.19.2 FTB Direwolf20 pack crashes when adding solar flux reborn

### ISSUE THREAD

**Issue by CrazyPizzaMan** [dragon-forge/SolarFluxReborn#5]
Hi there,

I've tried to add Solar Flux Reborn to the "FTB Presents Direwolf20 1.19" Pack in the FTB App but the game will not start with the mod added.

1st issue was that it would not download throught the FTB App.
2nd when i added it manually minecraft wouldn't start any more

Plz let me know what i do wrong.

The crashreport:

~~ REDACTED ~~

**Comment by Zeitheron** [comment]
Please ensure you are not using 1.19.3 build of the mod (AND HammerLib) by accident, and if you're using 19.3.X versions of both, please provide the logs.

**Comment by CrazyPizzaMan** [comment]
Im using SolarFluxReborn-1.19.2-19.3.7, but i dont know what hammerlib is. Do i need to add this as well?

[crash-2023-01-07_23.23.25-client.txt](https://github.com/dragon-forge/SolarFluxReborn/files/10367287/crash-2023-01-07_23.23.25-client.txt)

**Comment by Zeitheron** [comment]
HammerLib is a required library for the mod.
But the crash you're getting is because of MineTogether.

**Comment by CrazyPizzaMan** [comment]
With the HammerLib it started, but it needs Forge 43.2.0 or higher. Is there a way to update forge in a FTB modpack?

**Comment by Zeitheron** [comment]
Just...update it?
