### ISSUE TITLE
1.19.2 Server didn´t use the changed config

### ISSUE THREAD

**Issue by Realever** [dragon-forge/SolarFluxReborn#6]
hi,
i have a problem.I changed in the panels.cfg the Generation Rate for each solar panels and i uploaded the file on the server and restarted the server then.But after the server was done he used the default rate for like the solar panel tier 3.The solar panel was generation 32 fe instead 256 what i changed in the config file.I started then an singeplayer world to test it and there it was working.When i looking in the jei  there is written the changed rate but when i place it then he used the default rate.
I play on the minecraft version 1.19.2
forge version: 43.2.3
HammerLib: 1.19.2-19.3.46
Solar Flux Reborn: 1.19.2-19.3.7
![2023-01-16_02 29 48](https://user-images.githubusercontent.com/21349241/212580252-d454ab56-65be-4ab5-9c92-65a8cdbce9d6.png)

**Comment by Zeitheron** [comment]
I will investigate this soon, but right now I can not confirm nor deny this issue.

**Comment by Zeitheron** [comment]
Issue is confirmed. Working on a resolution.
